HelpProject/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HelpProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

HelpProject/Pages/Index.cshtml.cs
using HelpProject.Model;
using HelpProject.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelpProject.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        [TempData]
        public string Message { get; set; }

        public IndexModel(ILogger<IndexModel> logger, JsonFileUserService userService)
        {
            _logger = logger;
            UserService = userService;
        }

        public JsonFileUserService UserService { get; }
        public IEnumerable<User> Users { get; private set; }
        public UserLogin UserLogin { get; set; }

        public void OnGet() => Users = UserService.GetUsers();

        [BindProperty]
        public UserLogin userLogin { get; set; }

        public IActionResult OnPostUserLoginAsync()
        {
            Console.WriteLine("The request came");

            var Duser = UserService.AuthenticateUser(userLogin.UserName, userLogin.password);

            if (Duser != null && Duser.Password == userLogin.password)
            {

                string logedUser = Duser.UserName;
                return RedirectToPage("/Landing", new { logedUser });
                //return RedirectToAction("ThankYou", "Index");
                // Message = userLogin.UserName + " " + userLogin.password;
                // return RedirectToPage("/Index");
            }
            else
            {
                Message = $"Something went wrong User {userLogin.UserName} dont exit or password not correct";
                return RedirectToPage("./Index");
            }
        }
    }
}

HelpProject/Pages/Landing.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelpProject.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

HelpProject/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelpProject.Model;
using HelpProject.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace HelpProject.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly ILogger<RegisterModel> _logger;
        [TempData]
        public string Message { get; set; }
        [TempData]
        public string LogedUser { get; set; }


        public RegisterModel(ILogger<RegisterModel> logger, JsonFileUserService userService)
        {
            _logger = logger;
            UserService = userService;
        }

        public JsonFileUserService UserService { get; set; }
        public IEnumerable<User> Users { get; private set; }
        public new User User { get; set; }

        public void OnGet() => Users = UserService.GetUsers();

        [BindProperty]
        public User user { get; set; }

        public IActionResult OnPostUserRegisterAsync()
        {
            Console.WriteLine("The request came");
            if (user == null)
            {
                Message = $"Something went wron: User {user.UserName} not created";
                return RedirectToPage("./Register");
            }
                User Duser = UserService.AddUser(user);
                Console.WriteLine("Duser " + Duser);
                if (Duser != null)
                {
                    //ViewBag.username = string.Format("Successfully logged-in", user.UserName);

                    LogedUser = Duser.UserName;
                    return RedirectToPage("/Landing", new { LogedUser });
                    //return RedirectToAction("ThankYou", "Index");
                }
                else
                {
                    Message += $"Something went wrong, User {user.UserName} already exists";
                    return RedirectToPage("./Register");
                }
        }
    }
}

HelpProject/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    ViewData["Action"] = "Login";
}

<div>

    <div class="login">
        <h1>Login to Web App</h1>

        <form method="post">
            @if (@Model.Message != null)
            {
                <p class="text-danger">Message: @Model.Message</p>
            }

            <div asp-validation-summary="ModelOnly"></div>
            <label>Username</label>
            <p>
                <input asp-for="UserLogin.UserName" placeholder="Username">
                <span asp-validation-for="UserLogin.UserName" class="text-danger"></span>
            </p>
            <div asp-validation-summary="ModelOnly"></div>
            <label>Password</label>
            <p>
                <input asp-for="UserLogin.password" placeholder="Password">
                <span asp-validation-for="UserLogin.password" class="text-danger"></span>
            </p>
            <p class="remember_me">
                <label>
                    <input type="checkbox" name="remember_me" id="remember_me">
                    Remember me on this computer
                </label>
            </p>
            <p class="submit"><input type="submit" asp-page-handler="UserLogin" value="Login"></p>
            <hr />
            <p>Don't have account <a asp-area="" asp-page="/Register">Register</a>.</p>

        </form>

    </div>

</div>

HelpProject/Pages/Landing.cshtml
@page
@using HelpProject.Components
@model PrivacyModel
@{
    ViewData["Title"] = "Privacy Policy";
    ViewData["Action"] = "Logout";
    ViewData["user"] = Request.Query["logedUser"];
}
@(await Html.RenderComponentAsync<HelpPage>(RenderMode.ServerPrerendered))

<script src="_framework/blazor.server.js"></script>

HelpProject/Pages/Register.cshtml
@page
@model HelpProject.Pages.RegisterModel
@{
}
@{
    ViewData["Title"] = "Register";
    ViewData["Action"] = "Login";
}
<div>
    <div class="login">
        <h1>@ViewData["Title"]</h1>

        <form method="post">
            @if (@Model.Message != null)
            {
                <p class="text-danger">Message: @Model.Message</p>
            }
            @foreach (var user in Model.Users)
            {
                <!-- <p> @user.UserName</p> -->
            }
            <div asp-validation-summary="ModelOnly"></div>
            <label>First Name</label>
            <p>
                <input asp-for="User.FirstName" placeholder="First Name">
                <span asp-validation-for="User.FirstName" class="text-danger"></span>
            </p>
            <div asp-validation-summary="ModelOnly"></div>
            <label>Last Name</label>
            <p>
                <input asp-for="User.LastName" placeholder="Last Name">
                <span asp-validation-for="User.LastName" class="text-danger"></span>
            </p>
            <div asp-validation-summary="ModelOnly"></div>

            <label>Username</label>
            <p>
                <input asp-for="User.UserName" placeholder="Username">
                <span asp-validation-for="User.UserName" class="text-danger"></span>
            </p>
            <div asp-validation-summary="ModelOnly"></div>

            <label>Password</label>
            <p>
                <input asp-for="User.Password" placeholder="Password">
                <span asp-validation-for="User.Password" class="text-danger"></span>
            </p>

            <p class="submit"><input type="submit" asp-page-handler="UserRegister" value="Submit"></p>
            <hr />
        </form>
    </div>
</div>

HelpProject/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelpProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- <link rel="stylesheet" href="~/css/site.css" /> -->
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">HelpProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div style="float: right">
                <ul class="navbar-nav">
                    @if (@ViewData["user"] != null)
                    {
                        <li class="nav-item">Welcome @ViewData["user"]</li>
                    }
                    <li class="nav-item">
                        <a asp-area="" asp-page="/Index"> @ViewData["Action"]</a>
                    </li>
                </ul>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HelpProject
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>